spring:
  application:
    name: worker--notification

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "worker--notification"


aws:
  sns:
    topic:
      cobranca:
        arn: arn:aws:sns:us-east-1:000000000000:cobranca.notificacoes